### ISSUE TITLE
Inconsistent results for CUTEst with LBFGS()?

### ISSUE THREAD

**Issue by NicolasL-S** [JuliaSmoothOptimizers/CUTEst.jl#248] opened 2021-02-07 10:06 UTC
Hi all. While benchmarking my code, I've encountered a strange behavior optimizing "ARGLINB" or "ARGLINC" with LBFGS(). If I execute the following code (on Linux Ubuntu, Julia 1.5.3, CUTEst v0.10.3, NLPModels v0.13.2, Optim v1.2.3), after a few times, 
optimize gives inconsistent results and sometimes does not converge. It seems worse when I also recompile main(). So far, I haven't encountered the issue with other solvers and, as far as I can tell, the same thing only happened to me with "FLETCBV3", but it takes much longer to reproduce. Am I doing something wrong?

```
using CUTEst, Optim, NLPModels
function main()
   nlp = CUTEstModel("ARGLINB") #"ARGLINC"
   
   function ∇!(∇, x)
      ∇ .= collect(grad(nlp, x))
   end

   for run ∈ 1:10
      res = optimize(x -> obj(nlp, x), ∇!, nlp.meta.x0, LBFGS())
      print(Optim.g_calls(res), " ")
   end
   finalize(nlp)
end
main()
```

**Comment by dpo** [comment] 2021-02-07 18:42
Sorry, I'm not familiar with Optim. Here are just a few suggestions of things to look into (probably due to my lack of understanding of Optim):

1. Why is it necessary to `collect()` the gradient?
2. Have you tried `grad!(nlp, x, g)`?
3. Does the same happen with [our own LBFGS](https://github.com/JuliaSmoothOptimizers/JSOSolvers.jl/blob/master/src/lbfgs.jl)?
4. Something specific to Optim's LBFGS may be happening if you say you haven't been able to reproduce the issue with other solvers?!

Probably not so useful, sorry.

**Comment by NicolasL-S** [comment] 2021-02-10 23:05
Thanks for the advice. Indeed, collect() was superfluous, a relic from previous code. From what I can tell, with grad!(nlp, x, g), the problem still pops up. I have tried with your own LBFGS and not encountered any issues. But to be honest, I'm comparing optimization algorithms to the best in class and the Optim suite has very good implementations of the conjugate gradient and LBFGS with Hager-Zhang line search. Since I already benchmark with more than 80 CUTEst problems, missing one or two is not an issue. Rather, I posted to help point out an apparently rare bug in either Optim's LBFGS or in CUTEst.

**Comment by dpo** [comment] 2021-02-10 23:50
:-D Good luck.

**Comment by pkofod** [comment] 2021-02-11 10:15
I'll try to have a look.

**Comment by pkofod** [comment] 2021-02-11 10:44
Found the bug. Thanks a lot @NicolasL-S :)

**Comment by abelsiqueira** [comment] 2021-03-15 02:14
Looks like the issue was resolved. Closing.

**Closed by abelsiqueira** 2021-03-15 02:14 UTC

**Comment by NicolasL-S** [comment] 2021-03-15 08:54
> Found the bug. Thanks a lot @NicolasL-S :) Looking at it, it's actually something I'm surprised hasn't come up before.

Thanks a lot, it took me while to go back to it, but I can say it works perfectly now.
